const iceServers = [
  // First set of Google STUN servers
  { urls: "stun:stun.l.google.com:19302" },
  { urls: "stun:stun.l.google.com:5349" },
  { urls: "stun:stun1.l.google.com:3478" },
  { urls: "stun:stun1.l.google.com:5349" },
  { urls: "stun:stun2.l.google.com:19302" },
  { urls: "stun:stun2.l.google.com:5349" },
  { urls: "stun:stun3.l.google.com:3478" },
  { urls: "stun:stun3.l.google.com:5349" },
  { urls: "stun:stun4.l.google.com:19302" },
  { urls: "stun:stun4.l.google.com:5349" },

  // Second set of additional STUN servers
  // { urls: "stun:stun.1und1.de:3478" },
  // { urls: "stun:stun.gmx.net:3478" },
  // { urls: "stun:stun.12connect.com:3478" },
  // { urls: "stun:stun.12voip.com:3478" },
  // { urls: "stun:stun.2talk.co.nz:3478" },
  // { urls: "stun:stun.2talk.com:3478" },
  // { urls: "stun:stun.3clogic.com:3478" },
  // { urls: "stun:stun.3cx.com:3478" },
  // { urls: "stun:stun.a-mm.tv:3478" },
  // { urls: "stun:stun.aa.net.uk:3478" },
  // { urls: "stun:stun.acrobits.cz:3478" },
  // { urls: "stun:stun.actionvoip.com:3478" },
  // { urls: "stun:stun.advfn.com:3478" },
  // { urls: "stun:stun.aeta-audio.com:3478" },
  // { urls: "stun:stun.altar.com.pl:3478" },
  // { urls: "stun:stun.annatel.net:3478" },
  // { urls: "stun:stun.antisip.com:3478" },
  // { urls: "stun:stun.arbuz.ru:3478" },
  // { urls: "stun:stun.avigora.fr:3478" },
  // { urls: "stun:stun.awa-shima.com:3478" },
  // { urls: "stun:stun.b2b2c.ca:3478" },
  // { urls: "stun:stun.bahnhof.net:3478" },
  // { urls: "stun:stun.barracuda.com:3478" },
  // { urls: "stun:stun.bluesip.net:3478" },
  // { urls: "stun:stun.bmwgs.cz:3478" },
  // { urls: "stun:stun.botonakis.com:3478" },
  // { urls: "stun:stun.budgetsip.com:3478" },
  // { urls: "stun:stun.cablenet-as.net:3478" },
  // { urls: "stun:stun.callromania.ro:3478" },
  // { urls: "stun:stun.callwithus.com:3478" },
  // { urls: "stun:stun.chathelp.ru:3478" },
  // { urls: "stun:stun.cheapvoip.com:3478" },
  // { urls: "stun:stun.ciktel.com:3478" },
  // { urls: "stun:stun.cloopen.com:3478" },
  // { urls: "stun:stun.comfi.com:3478" },
  // { urls: "stun:stun.commpeak.com:3478" },
  // { urls: "stun:stun.comtube.com:3478" },
  // { urls: "stun:stun.comtube.ru:3478" },
  // { urls: "stun:stun.cope.es:3478" },
  // { urls: "stun:stun.counterpath.com:3478" },
  // { urls: "stun:stun.counterpath.net:3478" },
  // { urls: "stun:stun.datamanagement.it:3478" },
  // { urls: "stun:stun.dcalling.de:3478" },
  // { urls: "stun:stun.demos.ru:3478" },
  // { urls: "stun:stun.develz.org:3478" },
  // { urls: "stun:stun.dingaling.ca:3478" },
  // { urls: "stun:stun.doublerobotics.com:3478" },
  // { urls: "stun:stun.dus.net:3478" },
  // { urls: "stun:stun.easycall.pl:3478" },
  // { urls: "stun:stun.easyvoip.com:3478" },
  // { urls: "stun:stun.ekiga.net:3478" },
  // { urls: "stun:stun.epygi.com:3478" },
  // { urls: "stun:stun.etoilediese.fr:3478" },
  // { urls: "stun:stun.faktortel.com.au:3478" },
  // { urls: "stun:stun.freecall.com:3478" },
  // { urls: "stun:stun.freeswitch.org:3478" },
  // { urls: "stun:stun.freevoipdeal.com:3478" },
  // { urls: "stun:stun.gmx.de:3478" },
  // { urls: "stun:stun.gmx.net:3478" },
  // { urls: "stun:stun.gradwell.com:3478" },
  // { urls: "stun:stun.halonet.pl:3478" },
  // { urls: "stun:stun.hellonanu.com:3478" },
  // { urls: "stun:stun.hoiio.com:3478" },
  // { urls: "stun:stun.hosteurope.de:3478" },
  // { urls: "stun:stun.ideasip.com:3478" },
  // { urls: "stun:stun.infra.net:3478" },
  // { urls: "stun:stun.internetcalls.com:3478" },
  // { urls: "stun:stun.intervoip.com:3478" },
  // { urls: "stun:stun.ipcomms.net:3478" },
  // { urls: "stun:stun.ipfire.org:3478" },
  // { urls: "stun:stun.ippi.fr:3478" },
  // { urls: "stun:stun.ipshka.com:3478" },
  // { urls: "stun:stun.irian.at:3478" },
  // { urls: "stun:stun.it1.hr:3478" },
  // { urls: "stun:stun.ivao.aero:3478" },
  // { urls: "stun:stun.jumblo.com:3478" },
  // { urls: "stun:stun.justvoip.com:3478" },
  // { urls: "stun:stun.kanet.ru:3478" },
  // { urls: "stun:stun.kiwilink.co.nz:3478" },
  // { urls: "stun:stun.linea7.net:3478" },
  // { urls: "stun:stun.linphone.org:3478" },
  // { urls: "stun:stun.liveo.fr:3478" },
  // { urls: "stun:stun.lowratevoip.com:3478" },
  // { urls: "stun:stun.lugosoft.com:3478" },
  // { urls: "stun:stun.lundimatin.fr:3478" },
  // { urls: "stun:stun.magnet.ie:3478" },
  // { urls: "stun:stun.mgn.ru:3478" },
  // { urls: "stun:stun.mit.de:3478" },
  // { urls: "stun:stun.mitake.com.tw:3478" },
  // { urls: "stun:stun.miwifi.com:3478" },
  // { urls: "stun:stun.modulus.gr:3478" },
  // { urls: "stun:stun.myvoiptraffic.com:3478" },
  // { urls: "stun:stun.mywatson.it:3478" },
  // { urls: "stun:stun.nas.net:3478" },
  // { urls: "stun:stun.neotel.co.za:3478" },
  // { urls: "stun:stun.netappel.com:3478" },
  // { urls: "stun:stun.netgsm.com.tr:3478" },
  // { urls: "stun:stun.nfon.net:3478" },
  // { urls: "stun:stun.noblogs.org:3478" },
  // { urls: "stun:stun.noc.ams-ix.net:3478" },
  // { urls: "stun:stun.nonoh.net:3478" },
  // { urls: "stun:stun.nottingham.ac.uk:3478" },
  // { urls: "stun:stun.nova.is:3478" },
  // { urls: "stun:stun.on.net.mk:3478" },
  // { urls: "stun:stun.ooma.com:3478" },
  // { urls: "stun:stun.ooonet.ru:3478" },
  // { urls: "stun:stun.oriontelekom.rs:3478" },
  // { urls: "stun:stun.outland-net.de:3478" },
  // { urls: "stun:stun.ozekiphone.com:3478" },
  // { urls: "stun:stun.personal-voip.de:3478" },
  // { urls: "stun:stun.phone.com:3478" },
  // { urls: "stun:stun.pjsip.org:3478" },
  // { urls: "stun:stun.poivy.com:3478" },
  // { urls: "stun:stun.powerpbx.org:3478" },
  // { urls: "stun:stun.powervoip.com:3478" },
  // { urls: "stun:stun.ppdi.com:3478" },
  // { urls: "stun:stun.qq.com:3478" },
  // { urls: "stun:stun.rackco.com:3478" },
  // { urls: "stun:stun.rapidnet.de:3478" },
  // { urls: "stun:stun.rb-net.com:3478" },
  // { urls: "stun:stun.rixtelecom.se:3478" },
  // { urls: "stun:stun.rockenstein.de:3478" },
  // { urls: "stun:stun.rolmail.net:3478" },
  // { urls: "stun:stun.rynga.com:3478" },
  // { urls: "stun:stun.schlund.de:3478" },
  // { urls: "stun:stun.services.mozilla.com:3478" },
  // { urls: "stun:stun.sigmavoip.com:3478" },
  // { urls: "stun:stun.sip.us:3478" },
  // { urls: "stun:stun.sipdiscount.com:3478" },
  // { urls: "stun:stun.sipgate.net:10000" },
  // { urls: "stun:stun.sipgate.net:3478" },
  // { urls: "stun:stun.siplogin.de:3478" },
  // { urls: "stun:stun.sipnet.net:3478" },
  // { urls: "stun:stun.sipnet.ru:3478" },
  // { urls: "stun:stun.siportal.it:3478" },
  // { urls: "stun:stun.sippeer.dk:3478" },
  // { urls: "stun:stun.siptraffic.com:3478" },
  // { urls: "stun:stun.skylink.ru:3478" },
  // { urls: "stun:stun.sma.de:3478" },
  // { urls: "stun:stun.smartvoip.com:3478" },
  // { urls: "stun:stun.smsdiscount.com:3478" },
  // { urls: "stun:stun.snafu.de:3478" },
  // { urls: "stun:stun.softjoys.com:3478" },
  // { urls: "stun:stun.solcon.nl:3478" },
  // { urls: "stun:stun.solnet.ch:3478" },
  // { urls: "stun:stun.sonetel.com:3478" },
  // { urls: "stun:stun.soprano.com:3478" },
  // { urls: "stun:stun.spokn.com:3478" },
  // { urls: "stun:stun.spreed.me:3478" },
  // { urls: "stun:stun.sprocket4.com:3478" },
  // { urls: "stun:stun.sptel.com:3478" },
  // { urls: "stun:stun.srvs.de:3478" },
  // { urls: "stun:stun.stunall.com:3478" },
  // { urls: "stun:stun.sipregistrar.com:3478" },
  // {
  //   urls: "turn:your.turn.server:3478",
  //   username: "your-username",
  //   credential: "your-credential",
  // },
];

export default iceServers;
